//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintMood.Resources.Views.Shared {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Layoutru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal _Layoutru() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrintMood.UI.Resources.Views.Shared._Layoutru", typeof(_Layoutru).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Выберите тип футболки, загрузите свой принт и закажите.
        /// </summary>
        public static string Choose_a_shirt_type__upload_your_print_and_order_now {
            get {
                return ResourceManager.GetString("Choose a shirt type, upload your print and order now", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Наши контакты.
        /// </summary>
        public static string Contact_Us {
            get {
                return ResourceManager.GetString("Contact Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Контакты.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Авторские права &amp;copy; 2016 Владимир Трофимов. Все права защищены.
        /// </summary>
        public static string Copyright__copy__2016_Vladimir_Trofimov__All_rights_reserved_ {
            get {
                return ResourceManager.GetString("Copyright &copy; 2016 Vladimir Trofimov. All rights reserved.", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Домой.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Заказ.
        /// </summary>
        public static string Ordering {
            get {
                return ResourceManager.GetString("Ordering", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Print Mood - кто мы.
        /// </summary>
        public static string Print_Mood_who {
            get {
                return ResourceManager.GetString("Print Mood who", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to печать на майках, печать на футболках, печать на свитшотах, сайт заказа печати, кретивно, Print Mood.
        /// </summary>
        public static string printing_on_singlets__printing_on_t_shorts__printing_on_svitshots__print_order_website__creative__Print_Mood {
            get {
                return ResourceManager.GetString("printing on singlets, printing on t-shorts, printing on svitshots, print order we" +
                        "bsite, creative, Print Mood", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Печать на футболках, худи и свиншотах.
        /// </summary>
        public static string Printing_on_singlets__t_shirts_and_svitshots {
            get {
                return ResourceManager.GetString("Printing on singlets, t-shirts and svitshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Перейти на первую страницу.
        /// </summary>
        public static string Return_to_the_first_page {
            get {
                return ResourceManager.GetString("Return to the first page", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Владимир Трофимов.
        /// </summary>
        public static string Vladimir_Trofimov {
            get {
                return ResourceManager.GetString("Vladimir Trofimov", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Кто.
        /// </summary>
        public static string Who {
            get {
                return ResourceManager.GetString("Who", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Почему.
        /// </summary>
        public static string Why {
            get {
                return ResourceManager.GetString("Why", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Почему люди выбирают нас.
        /// </summary>
        public static string Why_people_choose_us {
            get {
                return ResourceManager.GetString("Why people choose us", resourceCulture);
            }
        }
    }
}
